blank_issues_enabled: false
contact_links:
  - name: ⁉️ Need help with electerm-web?
    url: https://github.com/electerm/electerm-web/discussions
    about: Please start a discussion before opening a bug.
